language: python
python:
  - "pypy"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
before_install:
  - wget https://dl.bintray.com/mitchellh/serf/0.6.4_linux_amd64.zip
  - unzip 0.6.4_linux_amd64.zip
  - ./serf agent &
  - sleep 1 ; ./serf tags -set foo=bar
install:
  - pip install msgpack-python
  - pip install -e . --use-mirrors
  - pip install coverage coveralls pep8
script:
  - coverage run --source=serfclient setup.py test
  - coverage report -m
  - pep8 --repeat --show-source serfclient tests
after_success:
  - coveralls
notifications:
  email: false
