sudo: false
language: python
python:
  - "pypy"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
before_install:
  - wget https://releases.hashicorp.com/serf/0.6.4/serf_0.6.4_linux_amd64.zip
  - unzip serf_0.6.4_linux_amd64.zip
  - ./serf agent &
  - sleep 1 ; ./serf tags -set foo=bar
install:
  - pip install 'coverage<4.0.0' coveralls pep8
  - python setup.py develop
script:
  - coverage run --source=serfclient setup.py test
  - coverage report -m
  - pep8 --repeat --show-source serfclient tests
after_success:
  - coveralls
notifications:
  email: false
