language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
before_install:
  - wget https://dl.bintray.com/mitchellh/serf/0.4.1_linux_amd64.zip
  - unzip 0.4.1_linux_amd64.zip
  - ./serf agent &
install:
  - pip install -e . --use-mirrors
  - pip install coverage
script:
  - coverage run --source=serfclient setup.py test
after_success:
  - coveralls
notifications:
  email: false
